// Ikoner fra Lucide (https://lucide.dev/icons/). Bare ikonene appen bruker importeres,
// slik at resten ikke havner i bygget. Navnene er Lucides egne (kebab-case).

import {
  Accessibility,
  Ambulance,
  BrickWall,
  BriefcaseMedical,
  Cable,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Construction,
  DoorClosed,
  DoorOpen,
  Droplet,
  Eraser,
  Fence,
  FireExtinguisher,
  Flag,
  Footprints,
  House,
  IceCreamCone,
  Info,
  KeyRound,
  Lightbulb,
  LocateFixed,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Menu,
  MicVocal,
  Move,
  Package,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  PlugZap,
  Plus,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  Shield,
  Speaker,
  SquareParking,
  Star,
  Store,
  Tag,
  Tent,
  Toilet,
  Trash2,
  TriangleAlert,
  Truck,
  Users,
  Utensils,
  Waves,
  X,
  Zap,
  type IconNode,
} from 'lucide';

const ICONS: Record<string, IconNode> = {
  accessibility: Accessibility,
  ambulance: Ambulance,
  'brick-wall': BrickWall,
  'briefcase-medical': BriefcaseMedical,
  cable: Cable,
  camera: Camera,
  car: Car,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  construction: Construction,
  'door-closed': DoorClosed,
  'door-open': DoorOpen,
  droplet: Droplet,
  eraser: Eraser,
  fence: Fence,
  'fire-extinguisher': FireExtinguisher,
  flag: Flag,
  footprints: Footprints,
  house: House,
  'ice-cream-cone': IceCreamCone,
  info: Info,
  'key-round': KeyRound,
  lightbulb: Lightbulb,
  'locate-fixed': LocateFixed,
  lock: Lock,
  'lock-open': LockOpen,
  'log-in': LogIn,
  'log-out': LogOut,
  menu: Menu,
  'mic-vocal': MicVocal,
  move: Move,
  package: Package,
  plane: Plane,
  'plane-landing': PlaneLanding,
  'plane-takeoff': PlaneTakeoff,
  'plug-zap': PlugZap,
  plus: Plus,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  route: Route,
  ruler: Ruler,
  shield: Shield,
  speaker: Speaker,
  'square-parking': SquareParking,
  star: Star,
  store: Store,
  tag: Tag,
  tent: Tent,
  toilet: Toilet,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  truck: Truck,
  users: Users,
  utensils: Utensils,
  waves: Waves,
  x: X,
  zap: Zap,
};

const escapeAttr = (v: string | number) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;');

/** SVG-markup for et ikon, til bruk i Leaflet-markører og andre steder utenfor React. */
export function iconSvg(name: string, size = 16, strokeWidth = 2): string {
  const node = ICONS[name] ?? ICONS.info;
  const children = node
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${escapeAttr(v as string)}"`).join(' ')}/>`)
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${children}</svg>`;
}

/** Lucide-ikon som React-komponent. Fargen arves fra teksten rundt. */
export function Icon({ name, size = 16, strokeWidth = 2, className = '' }: { name: string; size?: number; strokeWidth?: number; className?: string }) {
  return <span className={`icon ${className}`} dangerouslySetInnerHTML={{ __html: iconSvg(name, size, strokeWidth) }} />;
}
